[phases.setup]
nixPkgs = ['nodejs', 'npm', 'sqlite']

[phases.install]
cmds = [
    'npm ci',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'touch database/database.sqlite',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'