[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Packages.composer', 'sqlite']
aptPkgs = ['sqlite3']

[phases.install]
cmds = [
    'npm ci',
    'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'mkdir -p database',
    'touch database/database.sqlite',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
